# Generated by Django 2.1.4 on 2020-10-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pontos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
