# Generated by Django 2.1.4 on 2020-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='urltrade',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
