# Generated by Django 2.1.4 on 2020-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_urltrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
