# Generated by Django 2.1.4 on 2020-10-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201024_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagem',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
