# Generated by Django 2.1.4 on 2020-10-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_profile_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imagem',
        ),
    ]
