# Generated by Django 2.1.4 on 2020-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vencedor', models.CharField(max_length=200)),
                ('data_sorteio', models.DateField()),
                ('id_vencedor', models.IntegerField()),
                ('skin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('num_entradas', models.IntegerField()),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('participantes', models.TextField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('link', models.TextField()),
            ],
        ),
    ]
