# Generated by Django 2.1.4 on 2020-10-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='id_skin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
