# Generated by Django 2.1.4 on 2020-10-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_rifa_id_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='ativa',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
