# Generated by Django 2.1.4 on 2020-10-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0003_rifa_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='id_skin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='rifas.skin'),
        ),
    ]
