# Generated by Django 2.1.4 on 2020-10-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0004_auto_20201021_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='valor_entrada',
            field=models.IntegerField(),
        ),
    ]
