# Generated by Django 2.1.4 on 2020-10-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0005_auto_20201021_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='id_skin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin', to='rifas.skin'),
        ),
    ]
