# Generated by Django 2.1.4 on 2020-10-24 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0008_auto_20201022_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='id_skin',
        ),
        migrations.AddField(
            model_name='rifa',
            name='skin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rifas.skin'),
            preserve_default=False,
        ),
    ]
