# Generated by Django 2.1.4 on 2020-10-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0009_auto_20201024_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='num_part',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rifa',
            name='premium',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
