# Generated by Django 2.1.4 on 2020-10-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0011_auto_20201025_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='tem_ganhador',
        ),
        migrations.AlterField(
            model_name='rifa',
            name='ganhador',
            field=models.TextField(),
        ),
    ]
